name: Bundle Push

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  push-bundle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Lean
        run: |
          wget https://github.com/leanprover/lean4/releases/download/v4.7.0/lean-4.7.0-linux.tar.gz
          tar -xzf lean-4.7.0-linux.tar.gz
          echo "$PWD/lean-4.7.0-linux/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project
        run: lake build

      - name: Extract guards
        run: lake exe extract_guard

      - name: Create bundle
        run: |
          chmod +x bundle.sh
          ./bundle.sh bundle

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push bundle
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./extracted/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dataset-bundle:latest
            ghcr.io/${{ github.repository }}/dataset-bundle:${{ github.sha }}
            ghcr.io/${{ github.repository }}/dataset-bundle:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Upload bundle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dataset-bundle
          path: dist/
          retention-days: 30

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Dataset Safety Specs ${{ github.ref_name }}
          body: |
            ## Dataset Safety Specs Bundle

            This release contains the complete dataset safety specifications bundle including:

            - Lean formal specifications
            - Rust guards
            - Python guards
            - SentinelOps compliance bundle

            ### Bundle Contents
            - `dataset-safety-specs-*.tar.gz`: Complete bundle
            - `dataset-safety-specs-lean-*.tar.gz`: Lean specifications only
            - `sentinelops_compliance_bundle.zip`: SentinelOps compliance bundle

            ### Docker Image
            ```bash
            docker pull ghcr.io/${{ github.repository }}/dataset-bundle:${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
